// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using examenAPI_v2.Data;

#nullable disable

namespace ExamenAPI_v2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ExamenAPI_v2.Models.Pagos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("idCategory")
                        .HasColumnType("longtext");

                    b.Property<string>("registrationDate")
                        .HasColumnType("longtext");

                    b.Property<string>("tollName")
                        .HasColumnType("longtext");

                    b.Property<decimal>("value")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("vehiclePlate")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
